import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('Dataset_Ques_1_4.csv')
months = data['month_number']
total_profit = data['total_profit']
plt.figure(figsize=(10,6))
plt.plot(months, total_profit, label='Profit in each month', color='blue', marker='o')
plt.title('Company Profit per Month')
plt.xlabel('Month Number')
plt.ylabel('Total Profit')
plt.grid(True)
plt.show()
plt.figure(figsize=(10,6))
plt.plot(months, total_profit, label='Profit in each month', color='green', linestyle='--', linewidth=2, marker='s', markerfacecolor='red', markersize=8)
plt.title('Company Profit per Month with Styled Line Plot')
plt.xlabel('Month Number')
plt.ylabel('Total Profit')
plt.legend()
plt.grid(True)
plt.show()
plt.figure(figsize=(10,6))
plt.plot(months, data['facecream'], label='Face Cream Sales', marker='o')
plt.plot(months, data['facewash'], label='Face Wash Sales', marker='o')
plt.plot(months, data['toothpaste'], label='Toothpaste Sales', marker='o')
plt.plot(months, data['bathingsoap'], label='Bathing Soap Sales', marker='o')
plt.plot(months, data['shampoo'], label='Shampoo Sales', marker='o')
plt.plot(months, data['moisturizer'], label='Moisturizer Sales', marker='o')
plt.title('Sales Data of Different Products')
plt.xlabel('Month Number')
plt.ylabel('Sales Units in Number')
plt.legend()
plt.grid(True)
plt.show()
toothpaste_sales = data['toothpaste']
plt.figure(figsize=(10,6))
plt.scatter(months, toothpaste_sales, color='red')
plt.title('Toothpaste Sales Data')
plt.xlabel('Month Number')
plt.ylabel('Sales Units in Number')
plt.grid(True)
plt.show()
plt.figure(figsize=(10,6))
plt.bar(months - 0.2, data['facecream'], width=0.4, label='Face Cream Sales', align='center')
plt.bar(months + 0.2, data['facewash'], width=0.4, label='Face Wash Sales', align='center')
plt.title('Face Cream and Face Wash Sales Data')
plt.xlabel('Month Number')
plt.ylabel('Sales Units in Number')
plt.legend()
plt.grid(True)
plt.show()
plt.figure(figsize=(10,6))
plt.bar(months, data['bathingsoap'], color='green')
plt.title('Bathing Soap Sales Data')
plt.xlabel('Month Number')
plt.ylabel('Sales Units in Number')
plt.grid(True)
plt.savefig('bathing_soap_sales.png')
plt.show()
plt.figure(figsize=(10,6))
plt.hist(total_profit, bins=5, color='blue', edgecolor='black')
plt.title('Profit Distribution')
plt.xlabel('Profit')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()
total_sales = [data['facecream'].sum(), data['facewash'].sum(), data['toothpaste'].sum(), data['bathingsoap'].sum(), data['shampoo'].sum(), data['moisturizer'].sum()]
labels = ['Face Cream', 'Face Wash', 'Toothpaste', 'Bathing Soap', 'Shampoo', 'Moisturizer']
plt.figure(figsize=(8,8))
plt.pie(total_sales, labels=labels, autopct='%1.1f%%', startangle=140)
plt.title('Total Sales Data for Last Year')
plt.show()
plt.figure(figsize=(10,6))
plt.subplot(2, 1, 1)
plt.plot(months, data['bathingsoap'], label='Bathing Soap Sales', color='blue', marker='o')
plt.title('Bathing Soap Sales Data')
plt.ylabel('Sales Units')
plt.subplot(2, 1, 2)
plt.plot(months, data['facewash'], label='Face Wash Sales', color='green', marker='o')
plt.title('Face Wash Sales Data')
plt.xlabel('Month Number')
plt.ylabel('Sales Units')
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,6))
plt.stackplot(months, data['facecream'], data['facewash'], data['toothpaste'], data['bathingsoap'], data['shampoo'], data['moisturizer'], labels=labels)
plt.title('Sales Data Using Stack Plot')
plt.xlabel('Month Number')
plt.ylabel('Sales Units in Number')
plt.legend(loc='upper left')
plt.show()
